name: Update
on:
  workflow_dispatch:
  repository_dispatch:
    types: [docs-update]

jobs:
  readme:
    name: README
    runs-on: ubuntu-22.04
    env:
      ACTOR: ${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.actor) || github.actor }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npm run update
      - uses: EndBug/add-and-commit@v9
        with:
          add: docs/readme.md
          message: 'docs: update readme.md'
          author_name: ${{ env.ACTOR }}
          author_email: ${{ env.ACTOR }}@users.noreply.github.com
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
